### ISSUE TITLE
Final polish...

### ISSUE THREAD

**Issue by bublinak** [lukasvagner/EiotLib#1]
- Přesuň repo do kybernetického githubu
 - Uprav funkce ..._get a ..._set apod. na jména periferií
    - board.relay_get() -> board.relay()
    - board.relay_set(0/1) -> board.relay(0/1)
 - Přidej info jak nainstalovat (importovat) do projektu (že to má jít do složky /lib a tak)

**Comment by lukasvagner** [comment]
Done
